### PR TITLE
Move modules around

### PR DESCRIPTION
**Pull request by thomaseizinger**
# Description

See https://github.com/libp2p/rust-libp2p/pull/2289#issuecomment-1269220757.

This might be controversial :)
Open to feedback!

## Change checklist

- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] A changelog entry has been made in the appropriate crates

### CODE REVIEW

**Comment by thomaseizinger** [comment]
@kpp @elenaf9 Could I get some eyes on this? :)

**Comment by thomaseizinger** [comment]
I'll fix the intra-doc lint.

**Comment by kpp** [comment]
Well I took at look. Seems good

**Comment by elenaf9** [comment]
Ahh sorry somehow I missed that comment from you on libp2p#2289 Will take a look tomorrow. Mind merging latest upstream?

**Comment by thomaseizinger** [comment]
@elenaf9 I rebased it because the merge was too painful. Please have a look that I didn't accidentally undo any of your recent changes. I had a look through them and I think I got all of them!

**Comment by thomaseizinger** [comment]
> Well I took at look. Seems good

Sorry about the ping then, I wasn't aware.

**Review by elenaf9 — COMMENTED** [review]
Moving connection-related logic into a subdirectory, and the smaller changes from the first 3 commits look good to me.

But I am not convinced about `State`. I don't think the name is intuitive for something that includes poll-style code (polling sending / receiving on channels, polling a delay, ..). I would expect a `State` to be deterministic and only change when we actively inject events. However, with `poll_event` this is not the case.  
Because of this I would prefer to stick with the names `Connection` and `Muxer`. `Connection` includes all major logic for managing the connection, `Muxer` should just be a thin layer on top to implement the `StreamMuxer` trait. To me these names made sense when I first started reviewing the code.

But if you feel strongly about this or others are also in favor I am okay with renaming. 
@MarcoPolo  do you have an opinion?

**Comment by elenaf9** [comment]
FYI: I already cherry-picked the non-controversial first three commits, thanks!
I would leave this PR open to continue the above discussion, but in case that we do decide to do the renaming I'll just commit it directly myself.  That way we avoid annoying merge conflicts.

**Comment by MarcoPolo** [comment]
I agree with @elenaf9's points. I quite liked the names and found it easy to understand. "Okay let's look at how the StreamMuxer implementation... ah perfect it must be QuicMuxer". I certainly would have found it more confusing for it to be called `Connection`.

As for `Connection -> State`. `State` seems like a very generic term. `Connection` at least conveys this represents a connection to a remote peer.

**Comment by thomaseizinger** [comment]
I do feel strongly about this because the names are inspired by implementation details and not user-centric. For a user of the transport, the item they should get back from a dial or an upgrade is semantically a _connection_. All connections in rust-libp2p are multiplexed which is why they need to implement the `StreamMuxer`. Rust traits express capabilities of a component, not its identity[^1].

I am not attached to the name `State`, I agree that it is not great. It seemed the most logical to me given that it is a state machine that you need to drive but I am happy for it to have any other name, except `Connection`. I think whatever we return from `Transport` should be called `Connection`.

Also see [this](https://github.com/libp2p/rust-libp2p/discussions/2829) discussion for some more context.

[^1]: `StreamMuxer` by itself is a very OOP-influenced name, I think something like `Multiplex` would be better IMO.

**Comment by thomaseizinger** [comment]
We could probably get away with inlining `Connection` into what is currently called `Inner`. That would free up the name, perhaps reduce some indirection and we "nicely" nest the `quinn_proto::Connection` in our `Connection`. To make the file not as big, we could move the `Substream` implementation into its own `substream` module.

**Comment by elenaf9** [comment]
Inlining (the current) `Connection` into `Inner` sounds like a good solution. That was already something I considered doing in the past. 
Will draft a PR for it (including then also renaming `Muxer` to `Connection`) and ping you.

**Comment by elenaf9** [comment]
See #26.

**Comment by kpp** [comment]
@thomaseizinger shall we close this one?

**Pull request closed without merging**
